# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     Test1_Debug
#     Test1_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 5.1.2


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "Test1_Debug" configuration
#

ifeq ($(MAKECMDGOALS),Test1_Debug)

Test1_Debug : ./Debug/Test1.dxe 

./Debug/edit1.doj :./edit1.asm $(VDSP)/21k/include/def21060.h 
	@echo ".\edit1.asm"
	$(VDSP)/easm21k.exe .\edit1.asm -proc ADSP-21060 -file-attr ProjectName=Test1 -g -o .\Debug\edit1.doj -MM

./Debug/Test1.dxe :./Test1.ldf ./Debug/edit1.doj 
	@echo "Linking..."
	$(VDSP)/cc21k.exe .\Debug\edit1.doj -T .\Test1.ldf -L .\Debug -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\Test1.dxe -proc ADSP-21060 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),Test1_Debug_clean)

Test1_Debug_clean:
	-$(RM) ".\Debug\edit1.doj"
	-$(RM) ".\Debug\Test1.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


