# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     lab4_v2_Debug
#     lab4_v2_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 5.0


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "lab4_v2_Debug" configuration
#

ifeq ($(MAKECMDGOALS),lab4_v2_Debug)

lab4_v2_Debug : ./Debug/lab4_v2.dxe 

./Debug/asm.doj :./asm.asm ./constants.h $(VDSP)/21k/include/asm_sprt.h $(VDSP)/21k/include/def21060.h 
	@echo ".\asm.asm"
	$(VDSP)/easm21k.exe .\asm.asm -proc ADSP-21060 -file-attr ProjectName=lab4_v2 -g -o .\Debug\asm.doj -MM

Debug/code.doj :code.c $(VDSP)/21k/include/def21060.h $(VDSP)/21k/include/signal.h $(VDSP)/21k/include/stats.h constants.h 
	@echo ".\code.c"
	$(VDSP)/cc21k.exe -c .\code.c -file-attr ProjectName=lab4_v2 -g -structs-do-not-overlap -no-multiline -double-size-32 -warn-protos -proc ADSP-21060 -o .\Debug\code.doj -MM

./Debug/lab4_v2.dxe :$(VDSP)/21k/ldf/ADSP-21060.LDF $(VDSP)/21k/lib/060_hdr.doj ./Debug/asm.doj ./Debug/code.doj $(VDSP)/21k/lib/libc.dlb $(VDSP)/21k/lib/libdsp.dlb $(VDSP)/21k/lib/libio.dlb $(VDSP)/21k/lib/libcpp.dlb $(VDSP)/21k/lib/libeh.dlb $(VDSP)/21k/lib/libcpprt.dlb 
	@echo "Linking..."
	$(VDSP)/cc21k.exe .\Debug\asm.doj .\Debug\code.doj -L .\Debug -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\lab4_v2.dxe -proc ADSP-21060 -MM

endif

ifeq ($(MAKECMDGOALS),lab4_v2_Debug_clean)

lab4_v2_Debug_clean:
	-$(RM) ".\Debug\asm.doj"
	-$(RM) "Debug\code.doj"
	-$(RM) ".\Debug\lab4_v2.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


